github.com:
    oauth_token: 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
    user: ciosyam
    git_protocol: https
    users:
        ciosyam:
            oauth_token: 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
